[tool.poetry]
name = "genshin-checkin-helper"
version = "1.2.0"
description = "More than check-in for Genshin Impact."
authors = ["Bobby <bobby@fiery.me>"]

[tool.poetry.dependencies]
python = "^3.8"
genshinhelper = "2.1.3"
onepush = "1.1.1"
schedule = "^1.1.0"
nest-asyncio = "^1.5.6"
genshin = { git = "https://github.com/thesadru/genshin.py.git", rev = "f0dbef5e66e9885f7fcdae5a3e75cd97e1f64235" }
aiohttp = "^3.8.1"
pydantic = "=1.*"
anticaptchaofficial = "^1.0.53"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
